"""empty message

Revision ID: 3ee3c5a6479b
Revises: 4f8e01f8b4bc
Create Date: 2024-07-26 15:11:17.429563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee3c5a6479b'
down_revision = '4f8e01f8b4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('photos')

    # ### end Alembic commands ###
