"""empty message

Revision ID: 557212653d09
Revises: 5a368fbab324
Create Date: 2024-05-06 15:46:48.936114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557212653d09'
down_revision = '5a368fbab324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_followed_places',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'place_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_followed_places')
    # ### end Alembic commands ###
